# Generated by Django 3.1.1 on 2020-09-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryTitle', models.CharField(max_length=155)),
                ('entryRideDate', models.DateTimeField(verbose_name='Time of ride')),
                ('entryPublicDate', models.DateTimeField(verbose_name='Date published')),
                ('entryDist', models.DecimalField(decimal_places=2, max_digits=6)),
                ('entryAvgSpeed', models.IntegerField(default=0)),
                ('entryDescription', models.CharField(max_length=300)),
                ('entryCadence', models.IntegerField(default=0)),
                ('entryHeartRate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GpxTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryGpx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gpxster.entry')),
            ],
        ),
    ]
