# Generated by Django 3.1.1 on 2020-09-25 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gpxster', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpxtrack',
            name='entryGpx',
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='gpxDocument',
            field=models.FileField(blank=True, upload_to='gpxs/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='gpxTitle',
            field=models.CharField(default='Ride', max_length=100),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='gpxUploadedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
