# Generated by Django 3.1.1 on 2020-10-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpxster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrack',
            name='gpxUuid',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
