# Generated by Django 3.1.1 on 2020-09-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpxster', '0002_auto_20200925_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrack',
            name='gpxAuthor',
            field=models.CharField(default='default', editable=False, max_length=30),
        ),
    ]
