# Generated by Django 3.1.1 on 2021-02-12 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpxster', '0002_gpxtrack_gpxuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpxtrack',
            name='gpxAvgSpeed',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
