# Generated by Django 3.1.1 on 2020-09-26 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gpxster', '0003_gpxtrack_gpxauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpxtrack',
            name='gpxAvgSpeed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='gpxCadence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='gpxDist',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='gpxHeartRate',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gpxtrack',
            name='gpxRideDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
