# Generated by Django 3.1.1 on 2020-09-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gpxster', '0004_auto_20200926_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gpxtrack',
            name='gpxDocument',
        ),
    ]
